---
title: Data Cleaning
author: Reagan Tullis
execute: 
  cache: true
---
```{python}
#| echo: False
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
```

This page contains an overview of the data cleaning process for this sample analysis. Further information regarding the dataset can be found in data_info.md.  

For this analysis, my goal will be to predict the Metacritic score of a game based on the features included in this dataset. A Metacritic score is a 0-100 rating of a video game's overall quality.  

### Loading Data
Data was loaded from a .json file and transposed to standard format using pandas.
```{python}
games_raw = pd.read_json("data/games.json")
games_raw = games_raw.T
```
### Dropping Columns
For the purposes of this analysis, I will not be using unstructured text or image data. Columns containing this type of information were dropped, along with others that would not be useful for analytical purposes. See comments for further justification.
```{python}
games_dropped = games_raw.drop(columns=["name", # ID variable
                                        "detailed_description", # unstructured text
                                        "about_the_game", # unstructured text
                                        "short_description", # unstructured text
                                        "reviews", # unstructured text
                                        "header_image", # image data
                                        "website", # high cardinality & sparse representation
                                        "support_url", # high cardinality & sparse representation
                                        "support_email", # high cardinality & sparse representation
                                        "windows", # zero variance
                                        "metacritic_url", # high cardinality & sparse representation
                                        "notes", # unstructured text
                                        "packages", # not comparable across games
                                        "developers", # high cardinality & sparse representation
                                        "publishers", # high cardinality & sparse representation
                                        "screenshots", # image data
                                        "movies", # zero variance
                                        "user_score", # extreme missingness
                                        "score_rank", # extreme missingness
                                        "discount" # not reflective of historic data
                                        ])
```

### Missingness & Filtering Rows
This dataset does not contain any true missing values. Instead, 0 is a stand-in for missing values in numeric columns, and "" is a stand-in in string-valued columns. In most cases, this choice makes sense - "no achievements" and "zero achievements" mean the same thing - but in the case of `metacritic_score`, a real zero would indicate a bad score, so it is more appropriate to treat zeroes there as NAs. Furthermore, rows in which `metacritic_score == 0` lack an entry in the `metacritic_url` column, indicating that they were never reviewed by Metacritic. 

As for the remainder of the columns still included in the dataframe, I have verified that a zero truly means zero. The one remaining categorical column - `estimated_owners` - does not contain any placeholder values.  

Since `metacritic_score` is my target variable, I will be dropping rows in which `metacritic_score == 0`.  
```{python}
# drop all rows where the target variable is null
games_dropped = games_dropped[games_dropped["metacritic_score"] != 0]
```

### Typing Features
Due to the data being loaded from a `.json`, all features are initially typed as `object`. This had to be corrected manually.
```{python}
# sort features by desired type - this must be done manually
num_features = ["required_age", 
                "price",
                "dlc_count", 
                "metacritic_score", 
                "achievements", 
                "recommendations",
                "positive",
                "negative",
                "average_playtime_forever",
                "average_playtime_2weeks",
                "median_playtime_forever",
                "median_playtime_2weeks",
                "peak_ccu"
                ]

bool_features = ["mac", "linux"]

cat_features = ["estimated_owners"]

datetime_features = ["release_date"]

list_features = ["supported_languages",
                 "full_audio_languages",
                 "categories",
                 "genres"
                ]

dict_features = ["tags"]

# type features appropriately
games_typed= games_dropped.copy()

# numerics
for f in num_features:
    games_typed[f] = games_typed[f].astype(float)

# binary columns
for f in bool_features:
    games_typed[f] = games_typed[f].astype(int)

# categories
for f in cat_features:
    games_typed[f] = pd.Categorical(games_typed[f])

# datetimes
for f in datetime_features:
    games_typed[f] = pd.to_datetime(games_typed[f])
    games_typed[str(f) + "_year"] = games_typed[f].dt.year
    games_typed[str(f) + "_month"] = games_typed[f].dt.month
    games_typed[str(f) + "_day"] = games_typed[f].dt.day

# dict columns
for f in dict_features:
    # an empty list is used as a placeholder for games with no tags
    # so we can fill those in with an empty dict to be consistent with the rest of the column
    games_typed[f] = games_typed[f].apply(lambda x: {} if x == [] else x)
    f_expanded = pd.json_normalize(games_typed[f])
    # add prefix
    f_expanded = f_expanded.add_prefix(f + "_")
    # align index with original dataframe
    f_expanded.index = games_dropped.index
    # concatenate with original dataframe
    games_typed = pd.concat([games_typed, f_expanded], axis=1)
    # drop original dict column
    games_typed = games_typed.drop(columns=[f])

# fill NaNs created by empty dicts with 0s - this is appropriate since a missing tag is equivalent to a tag with a value of 0
games_typed = games_typed.fillna(0)
# (note that we had no NaNs in the original dataframe, so any NaNs in games_typed were created by the dict expansion process)
```  
### Multi-Hot Encoding
A number of columns (those included in `list_columns` above) contain a list of values. For instance, a value of `supported_languages` may be `["English", "Spanish"]`. These will need to be multi-hot encoded before I can use them in an analysis.

```{python}
games_encoded = games_typed.copy()
for f in list_features:
    mlb = MultiLabelBinarizer()
    transformed = mlb.fit_transform(games_typed[f])
    transformed_df = pd.DataFrame(transformed, columns=[f + "_" + str(c) for c in mlb.classes_], index=games_typed.index)
    games_encoded = pd.concat([games_encoded, transformed_df], axis=1)
    # drop original column
    games_encoded = games_encoded.drop(columns=[f])

```

With the data cleaning complete for now, I opted to save this cleaned dataframe as a `.csv` for ease of use later on.
```{python}
games_encoded.to_csv("data/games_clean.csv")
```
